// #78 P1c transport tests: the pull loop exercised over REAL HTTP
// against a fake peer, with REAL stores on both sides (the fake peer
// serves JSON generated by an actual SyncStore's outbox, so the full
// path — peer triggers -> outbox -> HTTP -> local LWW apply — runs).
//
// What this suite deliberately does NOT cover (declared ODD): the
// drogon handler bodies in AdminServerRoutesSync.inc. They are thin
// marshal-to-SyncStore shims over APIs tested here and in P1b; the
// client side of the protocol is what carries the state machine, and
// that is 100% real below (libcurl -> loopback socket -> libcurl).

#include "animus_kernel/PeerSyncService.h"
#include "animus_kernel/SqliteDataStore.h"
#include "animus_kernel/MemoryStore.h"
#include "animus_kernel/MemoryFileStore.h"
#include "animus_kernel/OntologyStore.h"
#include "animus_kernel/admin/DiaryManager.h"

#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <unistd.h>

#include <atomic>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <iostream>
#include <map>
#include <string>
#include <thread>
#include <vector>

using namespace animus::kernel;

namespace {

int g_failures = 0;

void Assert(bool condition, const std::string& msg) {
    if (!condition) {
        std::cerr << "  ASSERT FAILED: " << msg << "\n";
        g_failures++;
    }
}

// ---------------------------------------------------------------------------
// FakePeer: a tiny HTTP server on 127.0.0.1:<ephemeral>. One thread,
// connection-at-a-time, handler function per path prefix. Records every
// request (path + selected headers) for assertions.
// ---------------------------------------------------------------------------
class FakePeer {
public:
    using Handler = std::function<std::string(const std::string& path,
                                              const std::string& body)>;

    explicit FakePeer(Handler handler) : m_handler(std::move(handler)) {
        m_listen = socket(AF_INET, SOCK_STREAM, 0);
        int yes = 1;
        setsockopt(m_listen, SOL_SOCKET, SO_REUSEADDR, &yes, sizeof(yes));
        sockaddr_in addr{};
        addr.sin_family = AF_INET;
        addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
        addr.sin_port = 0;  // ephemeral
        bind(m_listen, reinterpret_cast<sockaddr*>(&addr), sizeof(addr));
        listen(m_listen, 16);
        socklen_t len = sizeof(addr);
        getsockname(m_listen, reinterpret_cast<sockaddr*>(&addr), &len);
        m_port = ntohs(addr.sin_port);
        m_url = "http://127.0.0.1:" + std::to_string(m_port);
        m_thread = std::thread([this] { Serve(); });
    }

    ~FakePeer() {
        m_stop = true;
        shutdown(m_listen, SHUT_RDWR);
        close(m_listen);
        if (m_thread.joinable()) m_thread.join();
    }

    const std::string& Url() const { return m_url; }

    struct Seen { std::string path; std::string nodeHeader; };
    std::vector<Seen> RequestsSnapshot() {
        std::lock_guard<std::mutex> lk(m_mutex);
        return m_requests;
    }

private:
    void Serve() {
        while (!m_stop) {
            int c = accept(m_listen, nullptr, nullptr);
            if (c < 0) break;
            struct timeval rt{0, 250 * 1000};  // 250ms recv timeout: the
            setsockopt(c, SOL_SOCKET, SO_RCVTIMEO, &rt, sizeof(rt));  // serve loop never wedges on an idle conn
            char buf[8192];
            ssize_t n = recv(c, buf, sizeof(buf) - 1, 0);
            if (n <= 0) { close(c); continue; }
            buf[n] = '\0';
            std::string req(buf);

            // Request line: METHOD SP PATH SP VERSION — take the PATH.
            size_t sp1 = req.find(' ');
            size_t sp2 = (sp1 == std::string::npos)
                ? std::string::npos : req.find(' ', sp1 + 1);
            std::string path = (sp1 == std::string::npos) ? req
                : req.substr(sp1 + 1,
                             (sp2 == std::string::npos)
                                 ? std::string::npos : sp2 - sp1 - 1);
            std::string nodeHeader;
            {
                size_t h = req.find("X-Animus-Node:");
                if (h != std::string::npos) {
                    size_t e = req.find("\r\n", h);
                    nodeHeader = req.substr(h + 14, e == std::string::npos
                        ? std::string::npos : e - h - 14);
                    while (!nodeHeader.empty() && nodeHeader.front() == ' ')
                        nodeHeader.erase(0, 1);
                }
            }
            {
                std::lock_guard<std::mutex> lk(m_mutex);
                m_requests.push_back({path, nodeHeader});
            }

            const std::string body = m_handler(path, "");
            std::string resp = "HTTP/1.1 200 OK\r\n"
                               "Content-Type: application/json\r\n"
                               "Connection: close\r\nContent-Length: ";
            resp += std::to_string(body.size());
            resp += "\r\n\r\n";
            resp += body;
            send(c, resp.c_str(), resp.size(), 0);
            close(c);
        }
    }

    Handler m_handler;
    int m_listen{-1};
    int m_port{0};
    std::string m_url;
    std::thread m_thread;
    std::atomic<bool> m_stop{false};
    std::mutex m_mutex;
    std::vector<Seen> m_requests;
};

// A real node-side store set (same shape as P1b's tests).
struct Node {
    std::string dbPath;
    SqliteDataStore dataStore;
    memory::MemoryStore memory;
    memory::MemoryFileStore files;
    ontology::OntologyStore ontology;
    DiaryStore diary;
    SyncStore sync;

    Node(uint64_t nodeId, const std::string& tag)
        : dbPath("/tmp/animus_psync_" + tag + ".db"),
          dataStore(dbPath), memory(&dataStore), files(&dataStore),
          ontology(&dataStore), diary(&dataStore), sync(&dataStore, nodeId) {
        std::filesystem::remove(dbPath);
        std::string err;
        if (!sync.EnsureSchema(&err)) {
            std::cerr << "  FATAL: sync init: " << err << "\n";
        }
    }
    ~Node() { std::filesystem::remove(dbPath); }
};

std::string OutboxJson(SyncStore& from, int64_t since, int64_t limit,
                       bool* hadMore) {
    const auto records = from.FetchOutboxSince(since, limit);
    const int64_t maxId = from.MaxOutboxId();
    std::string out = "{\"node_id\":" +
        std::to_string(from.LocalNodeId()) + ",\"records\":[";
    int64_t last = since;
    bool first = true;
    for (const auto& r : records) {
        if (!first) out += ",";
        first = false;
        // payload embedded as JSON string (escaped) — same wire shape the
        // admin route produces: payload stays a raw string.
        std::string esc;
        for (char ch : r.payload) {
            switch (ch) {
                case '"': esc += "\\\""; break;
                case '\\': esc += "\\\\"; break;
                case '\n': esc += "\\n"; break;
                case '\r': esc += "\\r"; break;
                case '\t': esc += "\\t"; break;
                default:
                    if (static_cast<unsigned char>(ch) < 0x20) {
                        char b[8]; snprintf(b, sizeof(b), "\\u%04x", ch);
                        esc += b;
                    } else esc += ch;
            }
        }
        out += "{\"outbox_id\":" + std::to_string(r.outbox_id) +
               ",\"origin_node\":" + std::to_string(r.origin_node) +
               ",\"table_name\":\"" + r.table_name + "\"" +
               ",\"row_id\":" + std::to_string(r.row_id) +
               ",\"op\":\"" + r.op + "\"" +
               ",\"payload\":\"" + esc + "\"" +
               ",\"unix_ms\":" + std::to_string(r.unix_ms) + "}";
        last = r.outbox_id;
    }
    out += "],\"max_id\":" + std::to_string(maxId) +
           ",\"has_more\":" + std::string(last < maxId ? "true" : "false") + "}";
    if (hadMore) *hadMore = (last < maxId);
    return out;
}

int64_t CountRows(IDataStore* store, const std::string& table) {
    auto q = store->Prepare("SELECT COUNT(*) FROM " + table);
    if (!q || !q->Step()) return -1;
    return q->ColumnInt64(0);
}

int64_t WriteMemory(memory::MemoryStore& m, const std::string& agent,
                    const std::string& text) {
    memory::Observation o;
    m.CreateDefaultLayersForAgent(agent);
    auto layers = m.ListLayersForAgent(agent);
    if (layers.empty()) return 0;
    o.layer_id = layers[0].id;
    o.agent_id = agent;
    o.text = text;
    auto obs = m.CreateObservationForAgent(agent, o);
    return obs.id;
}

} // namespace

int main() {
    std::cout << "=== PeerSyncServiceTests ===\n";

    // ------------------------------------------------------------------
    std::cout << "[sync-over-http] two real stores, real HTTP between\n";
    {
        Node a(1, "a");           // local node, has the service
        Node b(2, "b");           // remote node, feeds the fake server
        const int64_t bObsId = WriteMemory(b.memory, "ag", "hello from node 2");
        Assert(bObsId > 0, "B wrote an observation");
        Assert(b.sync.MaxOutboxId() > 0, "node B outbox non-empty");

        int64_t servedSince = -1;
        FakePeer peer([&](const std::string& path, const std::string&) {
            if (path.rfind("/api/v1/sync/handshake", 0) == 0) {
                return std::string("{\"protocol\":1,\"node_id\":2,"
                    "\"tables\":[\"observations\"],\"max_outbox_id\":"
                    + std::to_string(b.sync.MaxOutboxId()) + "}");
            }
            if (path.rfind("/api/v1/sync/outbox", 0) == 0) {
                size_t s = path.find("since=");
                int64_t since = s == std::string::npos
                    ? 0 : std::strtoll(path.c_str() + s + 6, nullptr, 10);
                servedSince = since;
                return OutboxJson(b.sync, since, 500, nullptr);
            }
            return std::string("{\"error\":\"not found\"}");
        });

        PeerSyncService svc(&a.sync, {peer.Url()}, "");
        const int applied = svc.SyncOnce();

        // First sync carries B's whole boot delta too (default layers,
        // layer_perspectives, mutation bookkeeping — triggers capture all
        // of it by design); assert >= 1 and verify OUR row landed below.
        Assert(applied >= 1, "changes applied over HTTP (got "
               + std::to_string(applied) + ")");
        Assert(a.sync.MaxOutboxId() >= 0, "A boots its own outbox via echo row");
        // The observation row landed on A.
        {
            auto q = a.dataStore.Prepare(
                "SELECT COUNT(*) FROM observations WHERE id = ?");
            q->BindInt64(1, bObsId);
            q->Step();
            Assert(q->ColumnInt64(0) == 1, "B's observation present on A");
        }
        Assert(servedSince == 0, "first pull started at cursor 0");
        Assert(a.sync.GetPeerCursor(2) == b.sync.MaxOutboxId(),
               "cursor persisted at B's max outbox id");

        Json::Value st = svc.StatusJson();
        Assert(st["peers"].isArray() && st["peers"].size() == 1,
               "status: one peer");
        Assert(st["peers"][0]["state"].asString() == "healthy",
               "status: healthy");
        Assert(st["peers"][0]["node_id"].asUInt64() == 2,
               "status: learned node id 2");

        // --- incremental: new write on B, only delta pulled ---
        Assert(WriteMemory(b.memory, "ag", "second from node 2") > 0,
               "second write on B");
        const int applied2 = svc.SyncOnce();
        // One observation write = observations row + mutation bookkeeping.
        Assert(applied2 >= 1, "second pass applied the delta (got "
               + std::to_string(applied2) + ")");
        Assert(servedSince > 0, "second pull resumed from cursor");

        auto reqs = peer.RequestsSnapshot();
        bool sawNodeHeader = false;
        for (const auto& r : reqs) {
            if (r.nodeHeader == "1") sawNodeHeader = true;
        }
        Assert(sawNodeHeader, "X-Animus-Node: 1 header sent on pulls");
    }

    // ------------------------------------------------------------------
    std::cout << "[echo-over-transport] peer reflects our own records back\n";
    {
        Node a(1, "echo");
        Assert(WriteMemory(a.memory, "ag", "local write") > 0,
               "local write for echo test");
        const int64_t outboxBefore = a.sync.MaxOutboxId();

        // Fake "peer" that answers handshake as node 2 but serves A's
        // OWN outbox records (misbehaving/echoing peer).
        FakePeer peer([&](const std::string& path, const std::string&) {
            if (path.rfind("/api/v1/sync/handshake", 0) == 0) {
                return std::string("{\"protocol\":1,\"node_id\":2,"
                    "\"tables\":[\"observations\"]}");
            }
            if (path.rfind("/api/v1/sync/outbox", 0) == 0) {
                size_t s = path.find("since=");
                int64_t since = s == std::string::npos
                    ? 0 : std::strtoll(path.c_str() + s + 6, nullptr, 10);
                return OutboxJson(a.sync, since, 500, nullptr);
            }
            return std::string("{}");
        });

        PeerSyncService svc(&a.sync, {peer.Url()}, "");
        const int applied = svc.SyncOnce();
        Assert(applied == 0, "echoed records apply nothing (got "
               + std::to_string(applied) + ")");
        Assert(CountRows(&a.dataStore, "observations") == 1,
               "row count unchanged after echo round-trip");
        // And the service doesn't wedge: a second pass is a no-op too.
        Assert(svc.SyncOnce() == 0, "second echo pass also a no-op");
        Assert(a.sync.MaxOutboxId() == outboxBefore,
               "A's outbox did not grow from echoes");
    }

    // ------------------------------------------------------------------
    std::cout << "[handshake-gate] protocol mismatch -> incompatible, no pull\n";
    {
        Node a(1, "proto");
        std::atomic<int> outboxHits{0};
        FakePeer peer([&](const std::string& path, const std::string&) {
            if (path.rfind("/api/v1/sync/handshake", 0) == 0) {
                return std::string("{\"protocol\":2,\"node_id\":2,"
                    "\"tables\":[]}");
            }
            if (path.rfind("/api/v1/sync/outbox", 0) == 0) {
                outboxHits++;
                return std::string("{\"records\":[],\"max_id\":0,"
                    "\"has_more\":false}");
            }
            return std::string("{}");
        });

        PeerSyncService svc(&a.sync, {peer.Url()}, "");
        svc.SyncOnce();
        Json::Value st = svc.StatusJson();
        Assert(st["peers"][0]["state"].asString() == "incompatible",
               "protocol mismatch flagged incompatible");
        Assert(outboxHits.load() == 0, "outbox never pulled after bad handshake");
        Assert(!st["peers"][0]["last_error"].asString().empty(),
               "last_error carries the mismatch reason");
        // Sticky: another pass doesn't even try the handshake again
        // (nodeId stays 0 -> it re-handshakes, still incompatible).
        svc.SyncOnce();
        st = svc.StatusJson();
        Assert(st["peers"][0]["state"].asString() == "incompatible",
               "incompatible is sticky across passes");
    }

    // ------------------------------------------------------------------
    std::cout << "[degrade-recover] failure streak -> down -> recovers\n";
    {
        Node a(1, "degrade");
        std::atomic<int> handshakeAttempts{0};
        std::atomic<bool> failing{true};
        FakePeer peer([&](const std::string& path, const std::string&) {
            if (path.rfind("/api/v1/sync/handshake", 0) == 0) {
                handshakeAttempts++;
                if (failing.load()) return std::string("{\"protocol\":1}");
                return std::string("{\"protocol\":1,\"node_id\":7,"
                    "\"tables\":[]}");
            }
            return std::string("{\"records\":[],\"max_id\":0,"
                "\"has_more\":false}");
        });

        PeerSyncService svc(&a.sync, {peer.Url()}, "");
        svc.SetFailuresBeforeDown(3);
        svc.SyncOnce();
        svc.SyncOnce();
        Json::Value st = svc.StatusJson();
        Assert(st["peers"][0]["state"].asString() == "connecting",
               "below streak threshold: still connecting");
        svc.SyncOnce();   // 3rd failure -> down
        st = svc.StatusJson();
        Assert(st["peers"][0]["state"].asString() == "down",
               "3 failures: state down");
        Assert(st["peers"][0]["consecutive_failures"].asInt() == 3,
               "failure streak counted");

        failing = false;
        svc.SyncOnce();   // recovers
        st = svc.StatusJson();
        Assert(st["peers"][0]["state"].asString() == "healthy",
               "recovered after peer came back");
        Assert(st["peers"][0]["consecutive_failures"].asInt() == 0,
               "streak reset on recovery");
        Assert(st["peers"][0]["node_id"].asUInt64() == 7,
               "node id learned post-recovery");
    }

    // ------------------------------------------------------------------
    std::cout << "[same-node-id] peer claiming our id is rejected\n";
    {
        Node a(1, "selfid");
        FakePeer peer([&](const std::string& path, const std::string&) {
            if (path.rfind("/api/v1/sync/handshake", 0) == 0) {
                return std::string("{\"protocol\":1,\"node_id\":1,"
                    "\"tables\":[]}");
            }
            return std::string("{\"records\":[],\"max_id\":0,"
                "\"has_more\":false}");
        });
        PeerSyncService svc(&a.sync, {peer.Url()}, "");
        svc.SyncOnce();
        Json::Value st = svc.StatusJson();
        Assert(st["peers"][0]["state"].asString() != "healthy",
               "peer claiming our own node id is never marked healthy");
        Assert(st["peers"][0]["last_error"].asString().find(
                   "OUR node id") != std::string::npos,
               "error names the configuration problem");
    }

    // ------------------------------------------------------------------
    std::cout << "[incoming-liveness] RecordIncomingPull bookkeeping\n";
    {
        Node a(1, "incoming");
        PeerSyncService svc(&a.sync, {}, "");
        svc.RecordIncomingPull(5, "http://10.0.0.5:8080");
        svc.RecordIncomingPull(5, "http://10.0.0.5:8080");
        svc.RecordIncomingPull(6, "http://10.0.0.6:8080");
        Json::Value st = svc.StatusJson();
        Assert(st["incoming"].size() == 2, "two distinct incoming pullers");
        bool saw5 = false;
        for (const auto& in : st["incoming"]) {
            if (in["node_id"].asUInt64() == 5) {
                saw5 = in["pulls"].asUInt64() == 2;
            }
        }
        Assert(saw5, "repeat pulls from node 5 counted");
    }

    if (g_failures == 0) {
        std::cout << "ALL PEER SYNC SERVICE TESTS PASSED\n";
        return 0;
    }
    std::cout << g_failures << " FAILURES\n";
    return 1;
}
